# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/w/Documents/Galaxy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/w/Documents/Galaxy/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/w/Documents/Galaxy/build/CMakeFiles /home/w/Documents/Galaxy/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/w/Documents/Galaxy/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Galaxian

# Build rule for target.
Galaxian: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Galaxian
.PHONY : Galaxian

# fast build rule for target.
Galaxian/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxian.dir/build.make CMakeFiles/Galaxian.dir/build
.PHONY : Galaxian/fast

#=============================================================================
# Target rules for targets named copy_assets

# Build rule for target.
copy_assets: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 copy_assets
.PHONY : copy_assets

# fast build rule for target.
copy_assets/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copy_assets.dir/build.make CMakeFiles/copy_assets.dir/build
.PHONY : copy_assets/fast

background.o: background.cpp.o
.PHONY : background.o

# target to build an object file
background.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxian.dir/build.make CMakeFiles/Galaxian.dir/background.cpp.o
.PHONY : background.cpp.o

background.i: background.cpp.i
.PHONY : background.i

# target to preprocess a source file
background.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxian.dir/build.make CMakeFiles/Galaxian.dir/background.cpp.i
.PHONY : background.cpp.i

background.s: background.cpp.s
.PHONY : background.s

# target to generate assembly for a file
background.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxian.dir/build.make CMakeFiles/Galaxian.dir/background.cpp.s
.PHONY : background.cpp.s

bullet.o: bullet.cpp.o
.PHONY : bullet.o

# target to build an object file
bullet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxian.dir/build.make CMakeFiles/Galaxian.dir/bullet.cpp.o
.PHONY : bullet.cpp.o

bullet.i: bullet.cpp.i
.PHONY : bullet.i

# target to preprocess a source file
bullet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxian.dir/build.make CMakeFiles/Galaxian.dir/bullet.cpp.i
.PHONY : bullet.cpp.i

bullet.s: bullet.cpp.s
.PHONY : bullet.s

# target to generate assembly for a file
bullet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxian.dir/build.make CMakeFiles/Galaxian.dir/bullet.cpp.s
.PHONY : bullet.cpp.s

constants.o: constants.cpp.o
.PHONY : constants.o

# target to build an object file
constants.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxian.dir/build.make CMakeFiles/Galaxian.dir/constants.cpp.o
.PHONY : constants.cpp.o

constants.i: constants.cpp.i
.PHONY : constants.i

# target to preprocess a source file
constants.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxian.dir/build.make CMakeFiles/Galaxian.dir/constants.cpp.i
.PHONY : constants.cpp.i

constants.s: constants.cpp.s
.PHONY : constants.s

# target to generate assembly for a file
constants.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxian.dir/build.make CMakeFiles/Galaxian.dir/constants.cpp.s
.PHONY : constants.cpp.s

enemy.o: enemy.cpp.o
.PHONY : enemy.o

# target to build an object file
enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxian.dir/build.make CMakeFiles/Galaxian.dir/enemy.cpp.o
.PHONY : enemy.cpp.o

enemy.i: enemy.cpp.i
.PHONY : enemy.i

# target to preprocess a source file
enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxian.dir/build.make CMakeFiles/Galaxian.dir/enemy.cpp.i
.PHONY : enemy.cpp.i

enemy.s: enemy.cpp.s
.PHONY : enemy.s

# target to generate assembly for a file
enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxian.dir/build.make CMakeFiles/Galaxian.dir/enemy.cpp.s
.PHONY : enemy.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxian.dir/build.make CMakeFiles/Galaxian.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxian.dir/build.make CMakeFiles/Galaxian.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxian.dir/build.make CMakeFiles/Galaxian.dir/main.cpp.s
.PHONY : main.cpp.s

player.o: player.cpp.o
.PHONY : player.o

# target to build an object file
player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxian.dir/build.make CMakeFiles/Galaxian.dir/player.cpp.o
.PHONY : player.cpp.o

player.i: player.cpp.i
.PHONY : player.i

# target to preprocess a source file
player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxian.dir/build.make CMakeFiles/Galaxian.dir/player.cpp.i
.PHONY : player.cpp.i

player.s: player.cpp.s
.PHONY : player.s

# target to generate assembly for a file
player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxian.dir/build.make CMakeFiles/Galaxian.dir/player.cpp.s
.PHONY : player.cpp.s

score.o: score.cpp.o
.PHONY : score.o

# target to build an object file
score.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxian.dir/build.make CMakeFiles/Galaxian.dir/score.cpp.o
.PHONY : score.cpp.o

score.i: score.cpp.i
.PHONY : score.i

# target to preprocess a source file
score.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxian.dir/build.make CMakeFiles/Galaxian.dir/score.cpp.i
.PHONY : score.cpp.i

score.s: score.cpp.s
.PHONY : score.s

# target to generate assembly for a file
score.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxian.dir/build.make CMakeFiles/Galaxian.dir/score.cpp.s
.PHONY : score.cpp.s

welcome.o: welcome.cpp.o
.PHONY : welcome.o

# target to build an object file
welcome.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxian.dir/build.make CMakeFiles/Galaxian.dir/welcome.cpp.o
.PHONY : welcome.cpp.o

welcome.i: welcome.cpp.i
.PHONY : welcome.i

# target to preprocess a source file
welcome.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxian.dir/build.make CMakeFiles/Galaxian.dir/welcome.cpp.i
.PHONY : welcome.cpp.i

welcome.s: welcome.cpp.s
.PHONY : welcome.s

# target to generate assembly for a file
welcome.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galaxian.dir/build.make CMakeFiles/Galaxian.dir/welcome.cpp.s
.PHONY : welcome.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... copy_assets"
	@echo "... Galaxian"
	@echo "... background.o"
	@echo "... background.i"
	@echo "... background.s"
	@echo "... bullet.o"
	@echo "... bullet.i"
	@echo "... bullet.s"
	@echo "... constants.o"
	@echo "... constants.i"
	@echo "... constants.s"
	@echo "... enemy.o"
	@echo "... enemy.i"
	@echo "... enemy.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... player.o"
	@echo "... player.i"
	@echo "... player.s"
	@echo "... score.o"
	@echo "... score.i"
	@echo "... score.s"
	@echo "... welcome.o"
	@echo "... welcome.i"
	@echo "... welcome.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

